#!/bin/bash
# I THINK THIS IS AN ACTION SIMILAR TO THE IPTABLES ONE WE REMOVED. THIS SHOULD BE PART OF THE DOCKERFILE
# REMEMBER THAT ACTIONS LIKE THIS WON'T PERSIST IF THE POD IS RESTARTED...
# WHY ARE IPS HARDCODED ANYWAY?
echo 200 sr >> /etc/iproute2/rt_tables
ip rule add from 60.60.0.0/24 table sr
ip route add default via 192.168.1.216 dev eth1 table sr
ip route flush cache
sysctl -w net.ipv4.ip_forward=1
apt-get update && apt-get install net-tools -y
ifconfig upfgtp0 mtu 1440
