#!/bin/sh -e
# Copyright 2020 Tata elxsi canonical@tataelxsi.onmicrosoft.com
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH=src
else
    export PYTHONPATH="src:$PYTHONPATH"
fi

flake8 src tests
python3 -m unittest -v "$@"
